site_name: Shift Framework
repo_url: https://github.com/ShiftSoftware/ShiftFrameworkWebsite
repo_name: ShiftSoftware/ShiftFrameworkWebsite
site_author: Shift Software
edit_uri: ShiftFrameworkWebsite/edit/master/docs/
copyright: Copyright &copy; 2023 Shift Software
theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/images/logo.png
  features:
    - navigation.tracking
    - navigation.tabs
    - content.code.copy
    - navigation.collapse
nav:
    - Home: 'index.md'
    - Back-end:
        - Getting Started: 'back-end/getting-started.md'
        - DTOs: 'back-end/dtos.md'
        - Entities: 'back-end/entities.md'
        - Repositories: 'back-end/repositories.md'
        - Controllers: 'back-end/controllers.md'
        - Completing API Setup: 'back-end/complete-api-setup.md'
        - Testing: 'back-end/testing.md'
        - Printing:
          - Printing One ToDo: 'back-end/printing/printing-one-todo.md'
          - Printing List of ToDos: 'back-end/printing/printing-todo-list.md'
        # - OData: 'back-end/odata.md'
        - Deployment:
          - Deploying to Staging: 'back-end/deployment/staging-deployment.md'
          - Pushing Staging to Production: 'back-end/deployment/production-deployment.md'
    - Front-end:
        - Getting Started: 'front-end/getting-started.md'
        - List: 'front-end/list.md'
        - Form: 'front-end/form.md'
        # - Type Auth:
        #     - Introduction: 'back-end/type-auth/introduction.md'
extra_css:
  - overrides/css/extra.css
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/ShiftSoftware
    - icon: fontawesome/brands/instagram 
      link: https://www.instagram.com/shift.software
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/shift-software
    - icon: fontawesome/brands/facebook 
      link: https://www.facebook.com/the.shift.software

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - pymdownx.mark
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true


